### ISSUE TITLE
Checking your install does not exist (returns 404)

### ISSUE THREAD

**Issue by jankaWIS** [PeerHerholz/workshop_weizmann#1]
Hi Peer,

I'm coming to your workshop at Weizmann in 10 days. I was checking your [instructions](https://peerherholz.github.io/workshop_weizmann/setup.html#checking-your-install) and just wanted to let you know that your page for checking installation doesn't exist.

`curl -s https://raw.githubusercontent.com/PeerHerholz/workshop_weizmann/master/check_ins`

returns 404.

**Comment by jankaWIS** [comment]
Speaking of 404, your link to opening an issue is wrong, you are missing an `s` at the end.
https://github.com/PeerHerholz/workshop_weizmann/issues

Now it returns another 404..

**Comment by jankaWIS** [comment]
One more thing regarding the same file (didn't want to open another issue), FYI on my machine, using:
```
conda install nibabel
```
results in
```
PackagesNotFoundError: The following packages are not available from current channels:

  - nibabel
```

The same goes for nilearn. Probably you want to recommend something like ([source](https://anaconda.org/conda-forge/nilearn)):
```
conda install -c conda-forge nilearn
```

or [pip](https://nilearn.github.io/introduction.html):
```
pip install -U --user nilearn
```

And one more note, `nibabel` is a dependency for `nilearn` so one can only install the latter.

**Comment by PeerHerholz** [comment]
Hi @jankaWIS,

ah yes. I added a short primer for such cases in the [setup instructions](https://peerherholz.github.io/workshop_weizmann/setup.html#some-quick-general-notes-on-instructions) but it might be worth further specifying it.
